### ISSUE TITLE
Can't connect to the local database

### ISSUE THREAD

**Issue by ankitrgadiya** [emarsden/pgmacs#9]
I tried connecting to a local database (running in Docker using upstream image) with M-x pgmacs.
The first issue I noticed was this log in the postgres:
```
    db-1  | 2024-12-08 18:58:41.524 UTC [48] STATEMENT:  CREATE EXTENSION IF NOT EXISTS vector
    db-1  | 2024-12-08 18:59:13.831 UTC [50] ERROR:  could not open extension control file "/usr/share/postgresql/14/extension/vector.control": No such file or directory
```

After commenting the `(pg-vector-setup con)` line, I'm getting this in the *Messages* buffer.
```
Whether to use an encrypted connection
Waiting for connection...
PostgreSQL NOTICE extension "hstore" already exists, skipping 
pg-bind: Wrong type argument: stringp, 97
```

I continue to see the `Retrieving PostgreSQL table list...` spinner in the echo area.

This is the backtrace after toggle-debug-on-error: https://gist.github.com/ankitrgadiya/d9ae038489e4f680e3037e2e61584312

**Comment by emarsden** [comment]
Thanks for testing! 

There is a problem in the `pg-table-owner` function from the pg-el library, that I don't understand. Can you check what version of pg-el you are using? For example with M-x package-version RET pg RET

**Comment by emarsden** [comment]
Could you also please point to the Docker image that you are using? I'd like to check why the error handling for setting up the vector extension is not working as expected (the error should be caught and handled).

**Comment by ankitrgadiya** [comment]
This is the pg version: pg 20241204.1441. This is being pulled from Melpa.
This is the use-package I used for installing pgmacs.

```
(use-package pgmacs
  :ensure t
  :vc (:url "https://github.com/emarsden/pgmacs" :rev "v0.18"))
```

This is the docker-compose I'm using for the database itself.
```
services:
  db:
    image: postgres:14
    restart: on-failure
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: PLACEHOLDER
    network_mode: host
    volumes:
      - $HOME/.local/var/postgresql:/var/lib/postgresql/data
```
